[package]
name = "Exu"
version = "0.1.0"
edition = "2021"
description = "The official interpreter of the Exu programming langauge."

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.10.1", features = ["pratt"] }
clap = { version = "4.5.41", features = ["derive"] }
