name: Setup Go
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: go.sum
